version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      testing-network:
        aliases:
          - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/web/posts"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  testing-network:
    driver: bridge