services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/web/posts"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Playwright test service
  tests:
    image: mcr.microsoft.com/playwright:v1.49.0-noble
    ipc: host  # Improve performance
    volumes:
      - ./e2e:/e2e  # Mount your e2e test directory
    working_dir: /e2e
    environment:
      - BASE_URL=http://app:8080
    depends_on:
      - app
    entrypoint: ["npx", "playwright", "test"]