// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Post struct {
	ID           string
	Title        string
	Description  string
	Url          string
	AuthorID     string
	Likes        int64
	ExpireTime   time.Time
	CreationTime time.Time
}

type User struct {
	ID    string
	Name  string
	Email string
}
